import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Order Management App",
  description: "Generated by Nayan Raj Shah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <header className="p-4 border-b flex justify-between">
            <Link href="/" className="font-bold">
              🍔 Food App
            </Link>

            <Link
              href="/cart"
              className="bg-black text-white px-3 py-1 rounded"
            >
              Go to Cart
            </Link>
          </header>

          {children}
        </CartProvider>
      </body>
    </html>
  );
}
